/**
 * CacheableResult support (SEP-2549) and deterministic list ordering.
 *
 * The single most aggregator-friendly change in 2026-07-28: cacheScope
 * "public" is explicit permission for a shared intermediary — a hub like this
 * one — to cache a downstream result.
 *
 * Two provenances, two policies:
 *
 *   - A list MERGED from N downstream servers may only claim the weakest
 *     guarantee any contributor gave it: narrowest scope, shortest TTL. One
 *     private downstream makes the whole merged list private.
 *
 *   - A list GENERATED by the hub itself contains no downstream content, so it
 *     is unconditionally public. This is the token-optimizer case: with the
 *     optimizer on, tools/list returns the static tools plus a single
 *     find-tools meta-tool rather than a merge of 1500 downstream definitions.
 *
 * The meta-tool's own results vary per query, but those come back from
 * tools/call, which carries no cache fields at all — so there is no conflict
 * with 2026-07-28's rule that list endpoints do not vary per connection.
 *
 * Deterministic ordering is a client-side win: identical bytes across repeated
 * tools/list calls keep the model's prompt cache warm. It matters most exactly
 * when the list is small and stable.
 */

export type CacheScope = 'public' | 'private';

export interface CacheableResult {
  ttlMs: number;
  cacheScope: CacheScope;
}

export const CACHEABLE_METHODS: readonly string[] = [
  'tools/list',
  'prompts/list',
  'resources/list',
  'resources/read',
  'resources/templates/list',
] as const;

export function isCacheableMethod(method: string): boolean {
  return CACHEABLE_METHODS.includes(method);
}

export function decorateCacheable<T extends object>(
  result: T,
  opts: { ttlMs: number; cacheScope: CacheScope },
): T & CacheableResult {
  return { ...result, ttlMs: opts.ttlMs, cacheScope: opts.cacheScope };
}

/** A merged result is public only if every contributor was. */
export function narrowestScope(scopes: CacheScope[]): CacheScope {
  if (scopes.length === 0) return 'private';
  return scopes.every((s) => s === 'public') ? 'public' : 'private';
}

/** A merged result is stale as soon as its earliest contributor is. */
export function shortestTtl(ttls: number[]): number {
  if (ttls.length === 0) return 0;
  return Math.min(...ttls);
}

/**
 * Cache policy for a list merged from downstream servers.
 *
 * No contributors means nothing is known to be cacheable, so the result is
 * private with a zero TTL rather than silently public-and-fresh.
 */
export function mergedCachePolicy(contributions: CacheableResult[]): CacheableResult {
  return {
    ttlMs: shortestTtl(contributions.map((c) => c.ttlMs)),
    cacheScope: narrowestScope(contributions.map((c) => c.cacheScope)),
  };
}

/**
 * Cache policy for a list the hub generated itself.
 *
 * Unconditionally public: there is no downstream content to leak between
 * tenants, so a shared intermediary may cache it.
 */
export function hubCachePolicy(ttlMs: number): CacheableResult {
  if (!Number.isFinite(ttlMs) || ttlMs < 0) {
    throw new Error(`hubCachePolicy: ttlMs must be a non-negative finite number, got ${ttlMs}`);
  }
  return { ttlMs, cacheScope: 'public' };
}

/**
 * Sort by raw codepoint, not locale: localeCompare would order differently
 * across runtimes and defeat the byte-identical guarantee the caching is for.
 */
export function sortToolsDeterministically<T extends { name: string }>(tools: T[]): T[] {
  return [...tools].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}
