/**
 * Session allocation for the stateful Streamable HTTP transport (deepsec findings
 * other-session-management-2accddc9bd / other-denial-of-service-8ed3a410b2).
 *
 * Session IDs are generated by the server at initialize, unknown IDs get 404,
 * nothing but a POST initialize allocates, failed connects leave nothing behind,
 * and a full pool rejects new sessions instead of evicting live ones.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import net from 'net';
import request from 'supertest';

vi.mock('@modelcontextprotocol/sdk/server/streamableHttp.js', () => ({
  StreamableHTTPServerTransport: vi.fn().mockImplementation(function (options: any) {
    return {
      options,
      handleRequest: vi.fn((_req: any, res: any) => {
        res.json({ jsonrpc: '2.0', result: 'reached-transport' });
      }),
      close: vi.fn(async () => {}),
    };
  }),
}));

import { resolveTransport } from '../src/middleware';
import { startStreamableHTTPServer } from '../src/streamable-http';
import { MAX_SESSIONS, SESSION_TTL_MS } from '../src/constants';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const INIT_BODY = {
  jsonrpc: '2.0',
  id: 1,
  method: 'initialize',
  params: {
    protocolVersion: '2025-06-18',
    capabilities: {},
    clientInfo: { name: 'deepsec-test', version: '1.0.0' },
  },
};

function fakeReq(method: string, body?: unknown, sessionId?: string) {
  return {
    method,
    body,
    headers: sessionId ? { 'mcp-session-id': sessionId } : {},
  };
}

function fakeRes() {
  const res: any = {
    statusCode: 200,
    headers: {} as Record<string, string>,
    body: undefined as any,
  };
  res.status = vi.fn((code: number) => { res.statusCode = code; return res; });
  res.json = vi.fn((payload: any) => { res.body = payload; return res; });
  res.setHeader = vi.fn((name: string, value: string) => { res.headers[name.toLowerCase()] = value; });
  return res;
}

function fakeSession(lastAccess: number) {
  return {
    transport: { close: vi.fn(async () => {}) } as any,
    server: { close: vi.fn(async () => {}) } as any,
    lastAccess,
  };
}

describe('resolveTransport (stateful)', () => {
  let server: any;
  let createServer: any;
  let sessions: Map<string, any>;

  beforeEach(() => {
    server = { connect: vi.fn(async () => {}) };
    createServer = vi.fn(() => server);
    sessions = new Map();
  });

  it('generates the session ID on the server for initialize', async () => {
    const res = fakeRes();
    const transport = await resolveTransport(fakeReq('POST', INIT_BODY), res, createServer, false, sessions);

    expect(transport).toBeTruthy();
    const issued = res.headers['mcp-session-id'];
    expect(issued).toMatch(UUID_RE);
    expect(sessions.has(issued)).toBe(true);
    expect(server.connect).toHaveBeenCalledTimes(1);
  });

  it('answers 404 for an unknown session ID instead of adopting it', async () => {
    const res = fakeRes();
    const transport = await resolveTransport(
      fakeReq('POST', INIT_BODY, 'attacker-chosen-id'),
      res,
      createServer,
      false,
      sessions
    );

    expect(transport).toBeNull();
    expect(res.statusCode).toBe(404);
    expect(sessions.size).toBe(0);
    expect(server.connect).not.toHaveBeenCalled();
  });

  it('reuses a known session and refreshes its last access', async () => {
    const existing = fakeSession(Date.now() - 1000);
    sessions.set('known', existing);

    const transport = await resolveTransport(fakeReq('POST', { jsonrpc: '2.0', id: 2, method: 'ping' }, 'known'), fakeRes(), createServer, false, sessions);

    expect(transport?.transport).toBe(existing.transport);
    expect(existing.lastAccess).toBeGreaterThan(Date.now() - 1000);
    expect(server.connect).not.toHaveBeenCalled();
  });

  it.each([
    ['GET without a session', fakeReq('GET')],
    ['POST non-initialize without a session', fakeReq('POST', { jsonrpc: '2.0', id: 2, method: 'tools/list' })],
    ['POST malformed initialize', fakeReq('POST', { jsonrpc: '2.0', id: 1, method: 'initialize', params: {} })],
    ['POST batch holding initialize plus another message', fakeReq('POST', [INIT_BODY, { jsonrpc: '2.0', id: 2, method: 'ping' }])],
  ])('does not allocate for %s', async (_label, req) => {
    const res = fakeRes();
    const transport = await resolveTransport(req, res, createServer, false, sessions);

    expect(transport).toBeNull();
    expect(res.statusCode).toBe(400);
    expect(sessions.size).toBe(0);
    expect(server.connect).not.toHaveBeenCalled();
  });

  it('leaves nothing in the map when connect fails', async () => {
    server.connect = vi.fn(async () => { throw new Error('Already connected to a transport'); });

    await expect(
      resolveTransport(fakeReq('POST', INIT_BODY), fakeRes(), createServer, false, sessions)
    ).rejects.toThrow('Already connected');
    expect(sessions.size).toBe(0);
  });

  it('rejects with 503 at capacity instead of evicting live sessions', async () => {
    const now = Date.now();
    for (let i = 0; i < MAX_SESSIONS; i++) sessions.set(`live-${i}`, fakeSession(now));
    const oldestLive = sessions.get('live-0');
    oldestLive.lastAccess = now - 60_000; // least recently used, but well within TTL

    const res = fakeRes();
    const transport = await resolveTransport(fakeReq('POST', INIT_BODY), res, createServer, false, sessions);

    expect(transport).toBeNull();
    expect(res.statusCode).toBe(503);
    expect(sessions.size).toBe(MAX_SESSIONS);
    expect(sessions.has('live-0')).toBe(true);
    expect(oldestLive.transport.close).not.toHaveBeenCalled();
    expect(server.connect).not.toHaveBeenCalled();
  });

  it('reclaims expired sessions at capacity to make room', async () => {
    const now = Date.now();
    for (let i = 0; i < MAX_SESSIONS; i++) sessions.set(`live-${i}`, fakeSession(now));
    const expired = fakeSession(now - SESSION_TTL_MS - 1000);
    sessions.set('live-0', expired);

    const res = fakeRes();
    const transport = await resolveTransport(fakeReq('POST', INIT_BODY), res, createServer, false, sessions);

    expect(transport).toBeTruthy();
    expect(sessions.has('live-0')).toBe(false);
    expect(expired.transport.close).toHaveBeenCalled();
    await vi.waitFor(() => expect(expired.server.close).toHaveBeenCalled());
    expect(sessions.has(res.headers['mcp-session-id'])).toBe(true);
    expect(sessions.size).toBe(MAX_SESSIONS);
  });
});

describe('Streamable HTTP handler does not allocate sessions for non-initialize traffic', () => {
  const originalEnv = process.env;
  let cleanup: (() => Promise<void>) | undefined;
  let base: string;

  function getFreePort(): Promise<number> {
    return new Promise((resolve, reject) => {
      const srv = net.createServer();
      srv.once('error', reject);
      srv.listen(0, 'localhost', () => {
        const { port } = srv.address() as net.AddressInfo;
        srv.close(() => resolve(port));
      });
    });
  }

  beforeEach(async () => {
    process.env = { ...originalEnv };
    const port = await getFreePort();
    const mockServer: any = { connect: vi.fn(async () => {}), close: vi.fn() };
    cleanup = await startStreamableHTTPServer(() => mockServer, { port });
    base = `http://localhost:${port}`;
  });

  afterEach(async () => {
    if (cleanup) {
      await cleanup().catch(() => {});
      cleanup = undefined;
    }
    process.env = originalEnv;
  });

  async function sessionCount(): Promise<number> {
    const res = await request(base).get('/health');
    return res.body.sessions;
  }

  it('GET without a session gets 400 and allocates nothing', async () => {
    const res = await request(base).get('/mcp');
    expect(res.status).toBe(400);
    expect(await sessionCount()).toBe(0);
  });

  it('GET with an unknown session gets 404 and allocates nothing', async () => {
    const res = await request(base).get('/').set('mcp-session-id', 'made-up');
    expect(res.status).toBe(404);
    expect(await sessionCount()).toBe(0);
  });

  it('unsupported HTTP methods get 405 and allocate nothing', async () => {
    const res = await request(base).put('/mcp').send({ test: 'data' });
    expect(res.status).toBe(405);
    expect(await sessionCount()).toBe(0);
  });

  it('DELETE without a session allocates nothing', async () => {
    const res = await request(base).delete('/mcp');
    expect(res.status).toBe(200);
    expect(await sessionCount()).toBe(0);
  });

  it('initialize returns a server-generated ID that later requests can use', async () => {
    const init = await request(base).post('/mcp').send(INIT_BODY);
    expect(init.status).toBe(200);
    const sessionId = init.headers['mcp-session-id'];
    expect(sessionId).toMatch(UUID_RE);

    const next = await request(base)
      .post('/mcp')
      .set('mcp-session-id', sessionId)
      .send({ jsonrpc: '2.0', id: 2, method: 'ping' });
    expect(next.status).toBe(200);
    expect(await sessionCount()).toBe(1);
  });
});
